pull_request_rules:
    - name: Automatic merge on approval
      actions:
        merge:
          strict: smart
          method: squash
          strict_method: merge
        request_reviews:
          users:
           - stefanfreitag
        delete_head_branch: {}
        dismiss_reviews: {}
      conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-success=Semantic Pull Request
      - status-success=Codacy/PR Quality Review
      - -closed
